-- 0000_baseline.sql — canonical Planit schema baseline.
-- Represents every currently deployed Planit-owned schema object. A fresh
-- database built from this baseline reproduces production (minus intentionally
-- excluded external artifacts) WITHOUT replaying abandoned intermediate designs.
-- Generated by squashing migrations 004,006,007,008,009,010,011,012,014,015,016,017,
-- 021,022,023,024,025 to their current (production) state, PLUS the
-- assistant_proposals / assistant_proposal_ops schema (originally
-- 026_assistant_proposals.sql on feature/assistant-phase-a, already deployed to
-- production and verified byte-for-byte against the linked prod schema on
-- 2026-07-31). Those assistant tables are already-deployed state, so they are
-- folded into the baseline — not carried as a forward migration.
-- Obsolete intermediate schema (001,002,003,005,013,019,020) is dropped entirely;
-- historical one-time transforms are folded into final DDL (e.g. public_pace_scans.started_at).
-- External/non-Planit object gh_trigger_log is intentionally NOT created.
-- Seed rows (checkpoints, community, club) live in supabase/seed.sql.
-- The eight *_updated_at triggers absent from prod (communities, igc_events, igc_players,
-- igc_rounds, igc_tee_times, igc_pairings, igc_comments, public_pace_checkpoints) are
-- intentionally NOT recreated; their updated_at columns remain without auto-maintenance,
-- matching production. A forward migration may restore them separately.


-- ============================================================
-- SOURCE: 004_bigdeal_private_app.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Big Deal private member/invite/event schema.

CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  email TEXT,
  phone TEXT,
  member_id UUID,
  invite_id UUID,
  is_system_admin BOOLEAN NOT NULL DEFAULT false,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE TABLE public.members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  display_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  golf_member_name TEXT NOT NULL,
  golf_member_id TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  invite_token TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'claimed', 'revoked')),
  claimed_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(member_id)
);

ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE SET NULL,
  ADD CONSTRAINT profiles_invite_id_fkey FOREIGN KEY (invite_id) REFERENCES public.invites(id) ON DELETE SET NULL;

CREATE TABLE public.events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_date DATE NOT NULL UNIQUE,
  course_name TEXT NOT NULL,
  registration_opens_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'locked', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "events_select_all" ON public.events FOR SELECT USING (true);

CREATE TABLE public.event_time_slots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  time_slot TEXT NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, time_slot)
);

ALTER TABLE public.event_time_slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "event_time_slots_select_all" ON public.event_time_slots FOR SELECT USING (true);

CREATE TABLE public.default_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tee_time_preferences TEXT[] NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

ALTER TABLE public.default_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "default_prefs_select_own" ON public.default_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "default_prefs_insert_own" ON public.default_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "default_prefs_update_own" ON public.default_preferences FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "default_prefs_delete_own" ON public.default_preferences FOR DELETE USING (auth.uid() = user_id);

CREATE TABLE public.event_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  tee_time_preferences TEXT[] NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, event_id)
);

ALTER TABLE public.event_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "event_prefs_select_own" ON public.event_preferences FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "event_prefs_insert_own" ON public.event_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "event_prefs_update_own" ON public.event_preferences FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "event_prefs_delete_own" ON public.event_preferences FOR DELETE USING (auth.uid() = user_id);

CREATE TABLE public.waitlist_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  display_name TEXT,
  phone TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.waitlist_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "waitlist_insert_any" ON public.waitlist_requests FOR INSERT WITH CHECK (true);

CREATE POLICY "members_select_admin" ON public.members
  FOR SELECT USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.is_admin = true OR profiles.is_system_admin = true)
    )
  );

CREATE POLICY "invites_select_admin" ON public.invites
  FOR SELECT USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.is_admin = true OR profiles.is_system_admin = true)
    )
  );

CREATE POLICY "invites_insert_admin" ON public.invites
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.is_admin = true OR profiles.is_system_admin = true)
    )
  );

CREATE POLICY "invites_update_admin" ON public.invites
  FOR UPDATE USING (
    EXISTS (
      SELECT 1
      FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.is_admin = true OR profiles.is_system_admin = true)
    )
  );

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'display_name', split_part(NEW.email, '@', 1)),
    NEW.email
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.validate_invite_token(
  signup_email TEXT,
  signup_token TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  invite_exists BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM public.invites invites
    JOIN public.members members ON members.id = invites.member_id
    WHERE invites.invite_token = signup_token
      AND invites.status = 'pending'
      AND (invites.expires_at IS NULL OR invites.expires_at > NOW())
      AND LOWER(members.email) = LOWER(signup_email)
  )
  INTO invite_exists;

  RETURN invite_exists;
END;
$$;

GRANT EXECUTE ON FUNCTION public.validate_invite_token(TEXT, TEXT) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.claim_invite_for_user(
  claim_user_id UUID,
  claim_email TEXT,
  claim_token TEXT,
  claim_display_name TEXT DEFAULT NULL
)
RETURNS TABLE(invite_id UUID, member_id UUID)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_invite public.invites%ROWTYPE;
  target_member public.members%ROWTYPE;
BEGIN
  SELECT invites.*
  INTO target_invite
  FROM public.invites invites
  JOIN public.members members ON members.id = invites.member_id
  WHERE invites.invite_token = claim_token
    AND invites.status = 'pending'
    AND (invites.expires_at IS NULL OR invites.expires_at > NOW())
    AND LOWER(members.email) = LOWER(claim_email)
  LIMIT 1;

  IF target_invite.id IS NULL THEN
    RETURN;
  END IF;

  SELECT *
  INTO target_member
  FROM public.members
  WHERE id = target_invite.member_id;

  UPDATE public.invites
  SET
    status = 'claimed',
    claimed_by_user_id = claim_user_id,
    updated_at = NOW()
  WHERE id = target_invite.id;

  UPDATE public.profiles
  SET
    member_id = target_member.id,
    invite_id = target_invite.id,
    display_name = COALESCE(claim_display_name, target_member.display_name, profiles.display_name),
    email = COALESCE(claim_email, profiles.email),
    phone = COALESCE(target_member.phone, profiles.phone),
    updated_at = NOW()
  WHERE id = claim_user_id;

  RETURN QUERY
  SELECT target_invite.id, target_member.id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.claim_invite_for_user(UUID, TEXT, TEXT, TEXT) TO authenticated;


-- ============================================================
-- SOURCE: 006_add_league_and_golf_ids.sql (verbatim; D/C/E statements removed below)
-- ============================================================
ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS league TEXT CHECK (league IN ('mens', 'womens'));

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS league TEXT CHECK (league IN ('mens', 'womens')),
  ADD COLUMN IF NOT EXISTS golf_event_id TEXT,
  ADD COLUMN IF NOT EXISTS golf_round_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS events_golf_round_id_key
  ON public.events (golf_round_id)
  WHERE golf_round_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS members_league_idx ON public.members (league);
CREATE INDEX IF NOT EXISTS events_league_event_date_idx ON public.events (league, event_date);


-- ============================================================
-- SOURCE: 007_add_registration_controls.sql (verbatim; D/C/E statements removed below)
-- ============================================================
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS registrations_paused BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS membership_revoked BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.event_preferences
  ADD COLUMN IF NOT EXISTS skip_registration BOOLEAN NOT NULL DEFAULT false;


-- ============================================================
-- SOURCE: 008_add_registration_runs.sql (verbatim; D/C/E statements removed below)
-- ============================================================
create table if not exists public.registration_runs (
  id uuid primary key default gen_random_uuid(),
  league text not null check (league in ('mens', 'womens')),
  event_date date not null,
  status text not null check (status in ('started', 'completed', 'failed')),
  task_count integer not null default 0,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb,
  unique (league, event_date)
);

create index if not exists registration_runs_league_event_date_idx
  on public.registration_runs (league, event_date desc);

alter table public.registration_runs enable row level security;

drop policy if exists "Allow service role full access to registration runs" on public.registration_runs;
create policy "Allow service role full access to registration runs"
  on public.registration_runs
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "Allow admins to read registration runs" on public.registration_runs;
create policy "Allow admins to read registration runs"
  on public.registration_runs
  for select
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and (profiles.is_admin = true or profiles.is_system_admin = true)
    )
  );


-- ============================================================
-- SOURCE: 009_add_member_email_override.sql (verbatim; D/C/E statements removed below)
-- ============================================================
alter table public.members
  add column if not exists roster_email text,
  add column if not exists email_override text;

create index if not exists members_roster_email_idx on public.members (lower(roster_email));
create index if not exists members_email_override_idx on public.members (lower(email_override));


-- ============================================================
-- SOURCE: 010_add_registration_run_results.sql (verbatim; D/C/E statements removed below)
-- ============================================================
create table if not exists public.registration_run_results (
  id uuid primary key default gen_random_uuid(),
  league text not null check (league in ('mens', 'womens')),
  event_date date not null,
  player_name text not null,
  player_member_id text not null,
  run_order integer not null default 0,
  attempted_times text[] not null default '{}'::text[],
  reserved_time text,
  success boolean not null default false,
  error text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league, event_date, player_name)
);

create index if not exists registration_run_results_league_event_date_idx
  on public.registration_run_results (league, event_date desc, run_order asc);

alter table public.registration_run_results enable row level security;

drop policy if exists "Allow service role full access to registration run results" on public.registration_run_results;
create policy "Allow service role full access to registration run results"
  on public.registration_run_results
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists "Allow admins to read registration run results" on public.registration_run_results;
create policy "Allow admins to read registration run results"
  on public.registration_run_results
  for select
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and (profiles.is_admin = true or profiles.is_system_admin = true)
    )
  );


-- ============================================================
-- SOURCE: 011_public_pace_scans.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Public QR checkpoint timing for unauthenticated scan flows.

CREATE TABLE IF NOT EXISTS public.public_pace_checkpoints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  course_name TEXT NOT NULL DEFAULT 'Interbay Golf Center',
  league TEXT CHECK (league IN ('mens', 'womens')),
  hole_number INT CHECK (hole_number > 0),
  scan_window_minutes INT NOT NULL DEFAULT 240 CHECK (scan_window_minutes > 0),
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.public_pace_checkpoints ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.public_pace_scans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  checkpoint_id UUID NOT NULL REFERENCES public.public_pace_checkpoints(id) ON DELETE CASCADE,
  event_id UUID REFERENCES public.events(id) ON DELETE SET NULL,
  event_date DATE NOT NULL,
  league TEXT CHECK (league IN ('mens', 'womens')),
  golf_event_id TEXT,
  golf_round_id TEXT,
  foursome_key TEXT NOT NULL,
  tee_time TEXT NOT NULL,
  actual_start_at TIMESTAMPTZ NOT NULL,
  player_names TEXT[] NOT NULL DEFAULT '{}',
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(checkpoint_id, event_date, foursome_key)
);

CREATE INDEX IF NOT EXISTS public_pace_checkpoints_token_idx
  ON public.public_pace_checkpoints (token)
  WHERE active = true;

CREATE INDEX IF NOT EXISTS public_pace_scans_leaderboard_idx
  ON public.public_pace_scans (event_date, checkpoint_id, scanned_at);

ALTER TABLE public.public_pace_scans ENABLE ROW LEVEL SECURITY;
-- checkpoint seed rows moved to supabase/seed.sql


-- ============================================================
-- SOURCE: 012_add_public_pace_ggid.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Store public QR timing runs keyed by the Golf Genius group ID.

ALTER TABLE public.public_pace_scans
  ADD COLUMN IF NOT EXISTS group_ggid TEXT,
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS finished_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS finished_checkpoint_id UUID REFERENCES public.public_pace_checkpoints(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS continuation_token TEXT;

ALTER TABLE public.public_pace_scans
  ALTER COLUMN tee_time DROP NOT NULL,
  ALTER COLUMN actual_start_at DROP NOT NULL;

CREATE INDEX IF NOT EXISTS public_pace_scans_group_ggid_idx
  ON public.public_pace_scans (event_date, group_ggid)
  WHERE group_ggid IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS public_pace_scans_continuation_token_key
  ON public.public_pace_scans (continuation_token)
  WHERE continuation_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS public_pace_scans_completed_leaderboard_idx
  ON public.public_pace_scans (event_date, checkpoint_id, finished_at)
  WHERE finished_at IS NOT NULL;


-- ============================================================
-- SOURCE: 014_igc_event_companion.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- IGC event companion shell.
-- Golf Genius remains the system of record; these tables store read-only imports
-- plus Planit-specific context and event memory.

CREATE TABLE IF NOT EXISTS public.communities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  short_name TEXT,
  description TEXT,
  brand_color TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "communities_select_all" ON public.communities;
CREATE POLICY "communities_select_all" ON public.communities FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.igc_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  community_id UUID NOT NULL REFERENCES public.communities(id) ON DELETE CASCADE,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  location_name TEXT,
  starts_on DATE,
  ends_on DATE,
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('draft', 'scheduled', 'active', 'completed', 'cancelled')),
  golf_genius_event_id TEXT,
  golf_genius_portal_id TEXT,
  golf_genius_portal_url TEXT,
  logistics JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_synced_at TIMESTAMPTZ,
  last_sync_status TEXT,
  last_sync_error TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS igc_events_community_id_idx ON public.igc_events (community_id);
CREATE INDEX IF NOT EXISTS igc_events_starts_on_idx ON public.igc_events (starts_on);
CREATE INDEX IF NOT EXISTS igc_events_golf_genius_event_id_idx
  ON public.igc_events (golf_genius_event_id)
  WHERE golf_genius_event_id IS NOT NULL;

ALTER TABLE public.igc_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_events_select_all" ON public.igc_events;
CREATE POLICY "igc_events_select_all" ON public.igc_events FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.igc_players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.igc_events(id) ON DELETE CASCADE,
  external_player_id TEXT NOT NULL,
  external_member_id TEXT,
  display_name TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  handicap_index NUMERIC,
  raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, external_player_id)
);

CREATE INDEX IF NOT EXISTS igc_players_event_id_idx ON public.igc_players (event_id);
ALTER TABLE public.igc_players ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_players_select_all" ON public.igc_players;
CREATE POLICY "igc_players_select_all" ON public.igc_players FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.igc_rounds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.igc_events(id) ON DELETE CASCADE,
  external_round_id TEXT NOT NULL,
  name TEXT NOT NULL,
  round_number INT,
  course_name TEXT,
  starts_on DATE,
  status TEXT,
  raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, external_round_id)
);

CREATE INDEX IF NOT EXISTS igc_rounds_event_id_idx ON public.igc_rounds (event_id);
ALTER TABLE public.igc_rounds ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_rounds_select_all" ON public.igc_rounds;
CREATE POLICY "igc_rounds_select_all" ON public.igc_rounds FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.igc_tee_times (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.igc_events(id) ON DELETE CASCADE,
  round_id UUID REFERENCES public.igc_rounds(id) ON DELETE CASCADE,
  external_tee_time_id TEXT NOT NULL,
  tee_time_label TEXT,
  starts_at TIMESTAMPTZ,
  tee TEXT,
  group_name TEXT,
  display_order INT NOT NULL DEFAULT 0,
  raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, external_tee_time_id)
);

CREATE INDEX IF NOT EXISTS igc_tee_times_event_round_idx ON public.igc_tee_times (event_id, round_id, display_order);
ALTER TABLE public.igc_tee_times ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_tee_times_select_all" ON public.igc_tee_times;
CREATE POLICY "igc_tee_times_select_all" ON public.igc_tee_times FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.igc_pairings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.igc_events(id) ON DELETE CASCADE,
  round_id UUID REFERENCES public.igc_rounds(id) ON DELETE CASCADE,
  tee_time_id UUID REFERENCES public.igc_tee_times(id) ON DELETE CASCADE,
  external_pairing_id TEXT NOT NULL,
  external_player_id TEXT,
  player_name TEXT NOT NULL,
  team_name TEXT,
  display_order INT NOT NULL DEFAULT 0,
  raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, external_pairing_id)
);

CREATE INDEX IF NOT EXISTS igc_pairings_tee_time_id_idx ON public.igc_pairings (tee_time_id, display_order);
ALTER TABLE public.igc_pairings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_pairings_select_all" ON public.igc_pairings;
CREATE POLICY "igc_pairings_select_all" ON public.igc_pairings FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.external_sync_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id UUID,
  external_id TEXT,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'success', 'failed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  error_message TEXT,
  summary JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS external_sync_runs_entity_idx
  ON public.external_sync_runs (provider, entity_type, entity_id, started_at DESC);

ALTER TABLE public.external_sync_runs ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.external_raw_payloads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sync_run_id UUID NOT NULL REFERENCES public.external_sync_runs(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  status_code INT,
  ok BOOLEAN NOT NULL DEFAULT false,
  payload JSONB,
  error_message TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS external_raw_payloads_sync_run_id_idx
  ON public.external_raw_payloads (sync_run_id, fetched_at);

ALTER TABLE public.external_raw_payloads ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.igc_leaderboard_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.igc_events(id) ON DELETE CASCADE,
  round_id UUID REFERENCES public.igc_rounds(id) ON DELETE SET NULL,
  external_sync_run_id UUID REFERENCES public.external_sync_runs(id) ON DELETE SET NULL,
  source_payload_id UUID REFERENCES public.external_raw_payloads(id) ON DELETE SET NULL,
  leaderboard_type TEXT NOT NULL DEFAULT 'event',
  snapshot_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  content_hash TEXT NOT NULL,
  rows JSONB NOT NULL DEFAULT '[]'::jsonb,
  summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, round_id, leaderboard_type, content_hash)
);

CREATE INDEX IF NOT EXISTS igc_leaderboard_snapshots_event_idx
  ON public.igc_leaderboard_snapshots (event_id, snapshot_at DESC);

ALTER TABLE public.igc_leaderboard_snapshots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_leaderboard_snapshots_select_all" ON public.igc_leaderboard_snapshots;
CREATE POLICY "igc_leaderboard_snapshots_select_all" ON public.igc_leaderboard_snapshots FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.igc_feed_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.igc_events(id) ON DELETE CASCADE,
  external_sync_run_id UUID REFERENCES public.external_sync_runs(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  dedupe_key TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, dedupe_key)
);

CREATE INDEX IF NOT EXISTS igc_feed_events_event_idx
  ON public.igc_feed_events (event_id, occurred_at DESC);

ALTER TABLE public.igc_feed_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_feed_events_select_all" ON public.igc_feed_events;
CREATE POLICY "igc_feed_events_select_all" ON public.igc_feed_events FOR SELECT USING (true);

CREATE TABLE IF NOT EXISTS public.igc_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  feed_event_id UUID NOT NULL REFERENCES public.igc_feed_events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.igc_comments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_comments_select_all" ON public.igc_comments;
CREATE POLICY "igc_comments_select_all" ON public.igc_comments FOR SELECT USING (true);
DROP POLICY IF EXISTS "igc_comments_insert_authenticated" ON public.igc_comments;
CREATE POLICY "igc_comments_insert_authenticated" ON public.igc_comments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.igc_reactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  feed_event_id UUID NOT NULL REFERENCES public.igc_feed_events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reaction TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(feed_event_id, user_id, reaction)
);

ALTER TABLE public.igc_reactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "igc_reactions_select_all" ON public.igc_reactions;
CREATE POLICY "igc_reactions_select_all" ON public.igc_reactions FOR SELECT USING (true);
DROP POLICY IF EXISTS "igc_reactions_insert_authenticated" ON public.igc_reactions;
CREATE POLICY "igc_reactions_insert_authenticated" ON public.igc_reactions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- community seed moved to supabase/seed.sql; stale sample igc_events row omitted.


-- ============================================================
-- SOURCE: 015_event_series_editions.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Event Series (recurring events)
CREATE TABLE event_series (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_public BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Event Editions (specific instances)
CREATE TABLE event_editions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_series_id UUID NOT NULL REFERENCES event_series(id) ON DELETE CASCADE,
    slug TEXT, -- optional custom slug
    year INTEGER NOT NULL,
    starts_on DATE,
    ends_on DATE,
    location_name TEXT,
    visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'club_members', 'invite_only')),
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'archived')),
    golf_genius_event_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(event_series_id, year)
);

-- RLS Policies
ALTER TABLE event_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_editions ENABLE ROW LEVEL SECURITY;

-- Public can view public series
CREATE POLICY "Public can view public series"
    ON event_series FOR SELECT
    USING (is_public = true);

-- Public can view public editions
CREATE POLICY "Public can view public editions"
    ON event_editions FOR SELECT
    USING (
        visibility = 'public'
        AND EXISTS (
            SELECT 1 FROM event_series
            WHERE event_series.id = event_editions.event_series_id
            AND event_series.is_public = true
        )
    );

-- Update triggers
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER event_series_updated_at
    BEFORE UPDATE ON event_series
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER event_editions_updated_at
    BEFORE UPDATE ON event_editions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ============================================================
-- SOURCE: 016_clubs_memberships.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Clubs
CREATE TABLE clubs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    short_name TEXT,
    description TEXT,
    logo_url TEXT,
    is_public BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Club follows
CREATE TABLE club_follows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, club_id)
);

-- Event-Club relationship
CREATE TABLE event_clubs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_series_id UUID NOT NULL REFERENCES event_series(id) ON DELETE CASCADE,
    club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    relationship_type TEXT DEFAULT 'host' CHECK (relationship_type IN ('host', 'sponsor', 'participating')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(event_series_id, club_id)
);

-- Club memberships
CREATE TABLE club_memberships (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'member' CHECK (role IN ('member', 'officer', 'admin')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'revoked')),
    invited_by UUID REFERENCES auth.users(id),
    invite_token TEXT, -- legacy Good to Go support
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, club_id)
);

-- Event follows
CREATE TABLE event_follows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    event_edition_id UUID NOT NULL REFERENCES event_editions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, event_edition_id)
);

-- Event participants
CREATE TABLE event_participants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_edition_id UUID NOT NULL REFERENCES event_editions(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    participant_type TEXT DEFAULT 'player' CHECK (participant_type IN ('player', 'spectator', 'organizer')),
    status TEXT DEFAULT 'registered' CHECK (status IN ('invited', 'registered', 'confirmed', 'cancelled')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(event_edition_id, user_id)
);

-- RLS Policies
ALTER TABLE clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_participants ENABLE ROW LEVEL SECURITY;

-- Clubs: public can view public clubs
CREATE POLICY "Public can view public clubs"
    ON clubs FOR SELECT
    USING (is_public = true);

-- Club follows: users manage their own
CREATE POLICY "Users manage their club follows"
    ON club_follows FOR ALL
    USING (user_id = auth.uid());

-- Club memberships: users view their own
CREATE POLICY "Users view their memberships"
    ON club_memberships FOR SELECT
    USING (user_id = auth.uid());

-- Event follows: users manage their own
CREATE POLICY "Users manage their event follows"
    ON event_follows FOR ALL
    USING (user_id = auth.uid());

-- Triggers
CREATE TRIGGER clubs_updated_at
    BEFORE UPDATE ON clubs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER club_memberships_updated_at
    BEFORE UPDATE ON club_memberships
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER event_participants_updated_at
    BEFORE UPDATE ON event_participants
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- IGC club seed moved to supabase/seed.sql


-- ============================================================
-- SOURCE: 017_feed_system.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Feed events (polymorphic activity)
CREATE TABLE feed_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subject_type TEXT NOT NULL CHECK (subject_type IN ('event_edition', 'club', 'trip', 'user')),
    subject_id UUID NOT NULL,
    actor_type TEXT DEFAULT 'system' CHECK (actor_type IN ('system', 'user', 'external_sync')),
    actor_id UUID REFERENCES auth.users(id),
    type TEXT NOT NULL, -- standings_updated, pairings_posted, registration_closes, etc.
    data JSONB DEFAULT '{}',
    visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'club_members', 'participants', 'admins')),
    dedupe_key TEXT, -- prevent duplicates: "standings_updated:seattle-cup:2026:r2"
    is_pinned BOOLEAN DEFAULT false,
    is_hidden BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Feed reactions
CREATE TABLE feed_reactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    feed_event_id UUID NOT NULL REFERENCES feed_events(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    reaction_type TEXT NOT NULL, -- emoji slug
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(feed_event_id, user_id, reaction_type)
);

-- Indexes for performance
CREATE INDEX idx_feed_events_subject ON feed_events(subject_type, subject_id);
CREATE INDEX idx_feed_events_created ON feed_events(created_at DESC);
CREATE INDEX idx_feed_events_dedupe ON feed_events(dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX idx_feed_events_pinned ON feed_events(is_pinned) WHERE is_pinned = true;

-- RLS Policies
ALTER TABLE feed_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE feed_reactions ENABLE ROW LEVEL SECURITY;

-- Feed events: public can view public events
CREATE POLICY "Public can view public feed events"
    ON feed_events FOR SELECT
    USING (visibility = 'public' AND is_hidden = false);

-- Feed reactions: users manage their own
CREATE POLICY "Users manage their reactions"
    ON feed_reactions FOR ALL
    USING (user_id = auth.uid());


-- ============================================================
-- SOURCE: 021_igc_league_tables.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- IGC League tables for weekly leaderboard and blog content
-- Stores processed Golf Genius data for live display

-- Events table (for selecting/viewing specific events)
CREATE TABLE igc_league_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_key TEXT NOT NULL CHECK (league_key IN ('mens', 'womens')),
    week_number INTEGER NOT NULL,
    gg_event_id TEXT NOT NULL,
    event_name TEXT NOT NULL,
    event_date DATE NOT NULL,
    course_name TEXT,
    status TEXT DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'live', 'finalized')),
    flights_finalized BOOLEAN DEFAULT false,
    finalized_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_key, week_number)
);

-- Weekly player performances (now with flight support)
CREATE TABLE igc_league_performances (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_key TEXT NOT NULL, -- 'mens_tuesday' or 'womens_wednesday'
    week_number INTEGER NOT NULL,
    event_id UUID REFERENCES igc_league_events(id) ON DELETE CASCADE,
    player_name TEXT NOT NULL,
    member_card_id TEXT,
    flight TEXT CHECK (flight IN ('A', 'B', 'C')), -- Only assigned after finalized
    event_name TEXT NOT NULL,
    event_date DATE,
    double_bogeys INTEGER DEFAULT 0,
    birdies INTEGER DEFAULT 0,
    weekly_position INTEGER NOT NULL, -- Overall position before flights
    flight_position INTEGER, -- Position within flight (once assigned)
    ranking_change INTEGER, -- positive = improved
    net_scores INTEGER[], -- nullable array for hole-by-hole
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_key, week_number, player_name)
);

-- Blog posts for weekly recaps (Substack integration)
CREATE TABLE igc_league_blog_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_key TEXT NOT NULL,
    week_number INTEGER NOT NULL,
    title TEXT,
    content TEXT NOT NULL,
    storylines JSONB DEFAULT '[]', -- structured storylines for easy editing
    pace_notes JSONB DEFAULT '[]',
    published BOOLEAN DEFAULT false,
    published_at TIMESTAMPTZ,
    substack_url TEXT, -- link to published post
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_key, week_number)
);

-- Season points standings (cached from GG)
CREATE TABLE igc_league_standings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_key TEXT NOT NULL,
    season_points_category_id TEXT NOT NULL,
    player_name TEXT NOT NULL,
    member_card_id TEXT,
    total_points INTEGER DEFAULT 0,
    rank INTEGER NOT NULL,
    events_played INTEGER DEFAULT 0,
    trend TEXT CHECK (trend IN ('up', 'down', 'stable')),
    last_week_rank INTEGER,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_key, player_name)
);

-- Indexes
CREATE INDEX idx_league_events_league ON igc_league_events(league_key);
CREATE INDEX idx_league_events_date ON igc_league_events(event_date);
CREATE INDEX idx_league_performances_league ON igc_league_performances(league_key);
CREATE INDEX idx_league_performances_week ON igc_league_performances(week_number);
CREATE INDEX idx_league_performances_event ON igc_league_performances(event_id);
CREATE INDEX idx_league_performances_player ON igc_league_performances(player_name);
CREATE INDEX idx_league_performances_flight ON igc_league_performances(flight);
CREATE INDEX idx_league_standings_league ON igc_league_standings(league_key);

-- RLS
ALTER TABLE igc_league_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE igc_league_performances ENABLE ROW LEVEL SECURITY;
ALTER TABLE igc_league_blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE igc_league_standings ENABLE ROW LEVEL SECURITY;

-- Public can view events, performances and standings
CREATE POLICY "Public can view league events"
    ON igc_league_events FOR SELECT
    USING (true);

CREATE POLICY "Public can view league performances"
    ON igc_league_performances FOR SELECT
    USING (true);

CREATE POLICY "Public can view league standings"
    ON igc_league_standings FOR SELECT
    USING (true);

-- Only admins can manage blog posts
CREATE POLICY "Admins can manage blog posts"
    ON igc_league_blog_posts FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
            AND (profiles.is_admin = true OR profiles.is_system_admin = true)
        )
    );

-- Triggers
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER league_events_updated_at
    BEFORE UPDATE ON igc_league_events
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER league_performances_updated_at
    BEFORE UPDATE ON igc_league_performances
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER league_blog_posts_updated_at
    BEFORE UPDATE ON igc_league_blog_posts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ============================================================
-- SOURCE: 022_capability_entitlements.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Capability entitlements + capability invites (Seattle Cup scouting access).
--
-- Model (see docs/access-onboarding-design-addendum.md):
--   PlanIt account (auth.users/profiles)
--     ├── IGC membership (OPTIONAL) — club_memberships, club=IGC. Created only
--     │   when a person is actually an IGC member/affiliate. NOT auto-created.
--     └── Seattle Cup scouting entitlement — feature_entitlements row below.
--
-- CRITICAL (§4): scouting does NOT require IGC membership. claim_capability_invite
-- and admin grants create ONLY a feature_entitlements row — never a
-- club_memberships row. The scouting gate checks the entitlement alone.
--
-- capability_invites is email-based and has NO dependency on the GG `members`
-- roster, so a scouting captain who is not a GG member (e.g. an outside
-- consultant) can still be invited and claim access. This mirrors the GTG
-- invites + claim_invite_for_user pattern (migration 004) but is separate and
-- does not touch members/profiles/invites.

-- ---------------------------------------------------------------------------
-- feature_entitlements: a granted capability for a user, scoped to a club.
-- ---------------------------------------------------------------------------
CREATE TABLE public.feature_entitlements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  -- Known keys today: 'seattle_cup_scouting'. Free-form text so future
  -- capabilities don't need a migration to add a value.
  feature_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  source TEXT NOT NULL CHECK (source IN ('invite', 'admin')),
  granted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  granted_at TIMESTAMPTZ DEFAULT NOW(),
  revoked_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  -- One entitlement record per user/club/feature. Re-grant after revocation
  -- upserts this row (flips status back to active) rather than duplicating.
  UNIQUE (user_id, club_id, feature_key)
);

CREATE INDEX feature_entitlements_user_idx ON public.feature_entitlements (user_id);
CREATE INDEX feature_entitlements_club_feature_status_idx
  ON public.feature_entitlements (club_id, feature_key, status);

ALTER TABLE public.feature_entitlements ENABLE ROW LEVEL SECURITY;

-- Users may read their own entitlements (so the access gate can run with the
-- user's own client). All writes go through the service-role client (admin
-- actions) or the claim RPC, both of which bypass RLS.
CREATE POLICY "Users view their own entitlements"
  ON public.feature_entitlements FOR SELECT
  USING (user_id = auth.uid());

CREATE TRIGGER feature_entitlements_updated_at
  BEFORE UPDATE ON public.feature_entitlements
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- capability_invites: email-based invite to claim a capability.
-- ---------------------------------------------------------------------------
CREATE TABLE public.capability_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id UUID NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  feature_key TEXT NOT NULL,
  email TEXT NOT NULL,
  invite_token TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'claimed', 'revoked', 'expired')),
  claimed_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  claimed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  display_name TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  -- One open invite per email/club/feature (re-invite upserts the pending row).
  UNIQUE (email, club_id, feature_key)
);

CREATE INDEX capability_invites_token_idx ON public.capability_invites (invite_token);
CREATE INDEX capability_invites_email_club_feature_idx
  ON public.capability_invites (email, club_id, feature_key);

ALTER TABLE public.capability_invites ENABLE ROW LEVEL SECURITY;

-- No direct user SELECT/INSERT/UPDATE/DELETE: invites are managed by admins
-- (service-role) and validated/claimed only through the SECURITY DEFINER RPCs
-- below. RLS therefore denies all user access by default.

CREATE TRIGGER capability_invites_updated_at
  BEFORE UPDATE ON public.capability_invites
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ---------------------------------------------------------------------------
-- validate_capability_invite: pre-auth check used by the signup/accept flow.
-- Returns true if a pending, unexpired invite matches the email + token.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.validate_capability_invite(
  p_email TEXT,
  p_token TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  invite_exists BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM public.capability_invites
    WHERE invite_token = p_token
      AND LOWER(email) = LOWER(p_email)
      AND status = 'pending'
      AND (expires_at IS NULL OR expires_at > NOW())
  )
  INTO invite_exists;

  RETURN invite_exists;
END;
$$;

GRANT EXECUTE ON FUNCTION public.validate_capability_invite(TEXT, TEXT) TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- claim_capability_invite: post-auth claim. Marks the invite claimed and
-- idempotently grants the feature entitlement. Does NOT create an IGC
-- club_memberships row (scouting does not require IGC membership).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.claim_capability_invite(
  p_user_id UUID,
  p_email TEXT,
  p_token TEXT,
  p_display_name TEXT DEFAULT NULL
)
RETURNS TABLE(invite_id UUID, granted_club_id UUID, granted_feature_key TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_invite_id UUID;
  v_club_id UUID;
  v_feature_key TEXT;
BEGIN
  SELECT ci.id, ci.club_id, ci.feature_key
  INTO v_invite_id, v_club_id, v_feature_key
  FROM public.capability_invites AS ci
  WHERE ci.invite_token = p_token
    AND LOWER(ci.email) = LOWER(p_email)
    AND ci.status = 'pending'
    AND (ci.expires_at IS NULL OR ci.expires_at > NOW())
  LIMIT 1;

  IF v_invite_id IS NULL THEN
    RETURN;
  END IF;

  -- Mark the invite claimed.
  UPDATE public.capability_invites
  SET
    status = 'claimed',
    claimed_by_user_id = p_user_id,
    claimed_at = NOW(),
    updated_at = NOW()
  WHERE id = v_invite_id;

  -- Grant the entitlement ONLY (no club_memberships row). Idempotent: if a
  -- revoked entitlement already exists for this user/club/feature, reactivate
  -- it rather than violating the unique constraint.
  INSERT INTO public.feature_entitlements (
    user_id, club_id, feature_key, status, source, granted_by, granted_at
  )
  VALUES (
    p_user_id, v_club_id, v_feature_key, 'active', 'invite', NULL, NOW()
  )
  ON CONFLICT (user_id, club_id, feature_key)
  DO UPDATE SET
    status = 'active',
    source = 'invite',
    granted_by = NULL,
    granted_at = NOW(),
    revoked_by = NULL,
    revoked_at = NULL,
    updated_at = NOW();

  RETURN QUERY
  SELECT v_invite_id, v_club_id, v_feature_key;
END;
$$;

GRANT EXECUTE ON FUNCTION public.claim_capability_invite(UUID, TEXT, TEXT, TEXT) TO authenticated;

-- ============================================================
-- SOURCE: 023_igc_league_rich_results.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Rich Golf Genius league results.
--
-- The 021 league schema stored only hole-by-hole net scores and a within-flight
-- rank, discarding the actual competition result (flight, points awarded, gross
-- scores, to-par, totals, purse, scoring status) and the cumulative season
-- points. This migration is PURELY ADDITIVE: it adds nullable columns to the
-- existing igc_league_events / igc_league_performances tables and introduces two
-- cache tables (season-points snapshot, member-card→name roster) so the league
-- pages can present authoritative GG data without re-deriving it from
-- birdie/double counts. No existing column is dropped, renamed, or retyped, so
-- current app code is unaffected.

-- Per-round event: link to the specific GG round + tournament and record
-- scoring status, so an actively scoring round can be detected and a round's
-- results can be re-fetched live without re-deriving the round by date.
ALTER TABLE igc_league_events
    ADD COLUMN gg_round_id TEXT,
    ADD COLUMN gg_tournament_id TEXT,
    ADD COLUMN results_released BOOLEAN,
    ADD COLUMN scored_at TIMESTAMPTZ;

-- Per-player round result: authoritative competition data straight from GG.
-- `flight` (A/B/C) and `flight_position` and `net_scores` already exist from
-- 021; `flight_name` stores GG's own scope label ("Flight 1/2/3") which does
-- not fit the existing A/B/C CHECK constraint. `position_label` keeps GG's raw
-- position ("1", "T2", "--") for display.
ALTER TABLE igc_league_performances
    ADD COLUMN flight_name TEXT,
    ADD COLUMN position_label TEXT,
    ADD COLUMN points NUMERIC(10,2),            -- authoritative points awarded this round
    ADD COLUMN gross_scores INTEGER[],           -- hole-by-hole gross
    ADD COLUMN to_par_net INTEGER[],             -- hole-by-hole net to-par
    ADD COLUMN to_par_gross INTEGER[],           -- hole-by-hole gross to-par
    ADD COLUMN net_total INTEGER,                -- net stroke total (out)
    ADD COLUMN gross_total INTEGER,              -- gross stroke total (out)
    ADD COLUMN to_par_net_total INTEGER,         -- net to-par total
    ADD COLUMN to_par_gross_total INTEGER,       -- gross to-par total
    ADD COLUMN purse TEXT,                       -- e.g. "$55.00"
    ADD COLUMN holes_completed INTEGER,          -- "thru": count of scored holes
    ADD COLUMN scorecard_status TEXT;            -- from GG scorecard_statuses

-- Season-points snapshot (authoritative cumulative race). `position` and
-- `total_points` come straight from GG's embedded event.season_points;
-- `previous_position` comes from the prior completed round's season_points;
-- `events_played` and `wins` are derived from the stored weekly performances
-- (authoritative position/flight data, not birdie counts). `points_behind` is
-- the gap to the leader. Separate from the legacy (unused) igc_league_standings
-- table, whose INTEGER total_points and CHECK trend do not fit GG's decimal
-- points.
CREATE TABLE igc_league_season_points (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_key TEXT NOT NULL CHECK (league_key IN ('mens', 'womens')),
    member_card_id TEXT NOT NULL,
    player_name TEXT,
    position INTEGER,
    previous_position INTEGER,
    total_points NUMERIC(10,2),
    events_played INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    points_behind NUMERIC(10,2),
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_key, member_card_id)
);

-- Member-card→name roster cache, from GG /events/{id}/roster. Needed because
-- GG's season_points identifies players only by member_card_id.
CREATE TABLE igc_league_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_key TEXT NOT NULL CHECK (league_key IN ('mens', 'womens')),
    member_card_id TEXT NOT NULL,
    name TEXT,
    email TEXT,
    handicap_index TEXT,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_key, member_card_id)
);

CREATE INDEX idx_league_events_round ON igc_league_events(gg_round_id);
CREATE INDEX idx_league_performances_flight_name ON igc_league_performances(flight_name);
CREATE INDEX idx_league_season_points_league_pos ON igc_league_season_points(league_key, position);
CREATE INDEX idx_league_season_points_member ON igc_league_season_points(league_key, member_card_id);
CREATE INDEX idx_league_members_member ON igc_league_members(league_key, member_card_id);

-- RLS: public can read league results/standings/roster (same posture as 021).
ALTER TABLE igc_league_season_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE igc_league_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view league season points"
    ON igc_league_season_points FOR SELECT
    USING (true);

CREATE POLICY "Public can view league members"
    ON igc_league_members FOR SELECT
    USING (true);

-- Note: no BEFORE UPDATE trigger on the two new tables. They carry synced_at
-- (set explicitly by the sync on every upsert), not updated_at, and the
-- shared update_updated_at() function from 021 references NEW.updated_at.

-- ============================================================
-- SOURCE: 024_igc_league_gross_net_results.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Corrective, purely additive migration for IGC league results.
--
-- Two bugs found by validating the persisted data against Golf Genius:
--
--   1. SEASON POINTS WERE WEEKLY, NOT CUMULATIVE. The 023 sync stored the
--      latest round's `event.season_points[].total_points` as if it were the
--      cumulative season total. In GG that field is the points awarded IN THAT
--      ROUND (max 500), not the running total. The authoritative cumulative
--      standings (e.g. Hans Olson ≈ 4141.84) are the SUM of weekly
--      total_points across every completed round AND both the Gross and Net
--      competitions (they share one season_point_category). No GG endpoint
--      exposes the cumulative total directly (all candidates 404), so the sync
--      now accumulates it. No schema change is needed for this fix —
--      igc_league_season_points.total_points already holds the right shape; the
--      sync just populates it correctly.
--
--   2. ONLY ONE COMPETITION WAS PERSISTED. The 023 sync picked a single
--      tournament (Net) and discarded the Gross competition. GG models a league
--      round as TWO individual tournaments — "Gross Regular Season" / "Net
--      Regular Season" (men's), "Gross Individual Play" / "Net Individual
--      Play" (women's) — each scoped by flight (men's: Flight 1/2/3; women's:
--      Overall). The SAME player appears in both with an IDENTICAL hole-by-hole
--      scorecard; only the result (position, points, purse) differs. So the
--      scorecard is ONE fact and the Gross/Net placements are two result
--      memberships of it. This migration adds a result-membership table so both
--      competitions are preserved without duplicating the scorecard.
--
-- Additive only: no existing column is dropped/renamed/retyped. The 023
-- scorecard columns on igc_league_performances remain (the scorecard fact); the
-- per-competition result now lives in igc_league_results.

-- Link each event row to BOTH individual tournaments so live re-fetch can get
-- both competitions. gg_tournament_id (023) is retained and holds the Net
-- tournament id (null for team weeks), so the existing team-event detection
-- (gg_tournament_id IS NULL) keeps working unchanged.
ALTER TABLE igc_league_events
    ADD COLUMN gg_gross_tournament_id TEXT,
    ADD COLUMN gg_net_tournament_id TEXT;

-- Per-player-round × competition result membership. The scorecard itself
-- (gross/net hole scores, to-par, totals, holes completed) lives ONCE in
-- igc_league_performances; this table holds only the competition-specific
-- placement: which competition (gross/net), which flight, finishing position,
-- points awarded, and purse. Two rows per player-round for individual weeks
-- (gross + net); none for team/scramble weeks.
CREATE TABLE igc_league_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_key TEXT NOT NULL CHECK (league_key IN ('mens', 'womens')),
    week_number INTEGER NOT NULL,
    event_id UUID REFERENCES igc_league_events(id) ON DELETE CASCADE,
    member_card_id TEXT NOT NULL,        -- league aggregates always carry this
    player_name TEXT NOT NULL,
    competition TEXT NOT NULL CHECK (competition IN ('gross', 'net')),
    flight_name TEXT,                    -- "Flight 1/2/3" (men's) / "Overall" (women's)
    position_label TEXT,                 -- GG raw "1", "T2", "--"
    flight_position INTEGER,             -- parsed numeric finishing position
    points NUMERIC(10,2),                -- men's weekly points; NULL for women's
    purse TEXT,                          -- "$55.00"
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(league_key, week_number, member_card_id, competition)
);

CREATE INDEX idx_league_results_lookup ON igc_league_results(league_key, week_number, competition);
CREATE INDEX idx_league_results_flight ON igc_league_results(league_key, week_number, flight_name, competition);
CREATE INDEX idx_league_results_member ON igc_league_results(league_key, member_card_id);

ALTER TABLE igc_league_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can view league results"
    ON igc_league_results FOR SELECT
    USING (true);

-- ============================================================
-- SOURCE: 025_activity_system.sql (verbatim; D/C/E statements removed below)
-- ============================================================
-- Lightweight durable activity feed for PlanIt. V1 is Seattle Cup scouting only:
-- a compact, per-user-unread activity inbox in the authenticated app shell.
--
-- planit.golf OWNS this layer (user-facing activity + unread state + realtime
-- delivery). The authoritative scouting domain state (candidate state,
-- availability, notes) stays in the planit-ai project; activity_events is an
-- audit/notification projection authored at the planit.golf Server Action choke
-- point AFTER a successful planit-ai write. It is NOT a second source of
-- candidate state / availability / notes — it records who changed what, for an
-- inbox, nothing more.
--
-- The envelope is intentionally generic (feature + activity_type + subject) so
-- future league / trips / events / roster activity can reuse it without an event
-- bus or notification framework. Only seattle_cup_scouting activity is produced
-- in V1, and activity_type is CHECK-constrained to the three approved types.

-- ---------------------------------------------------------------------------
-- Entitlement helper (defined first; the activity_events SELECT policy uses it).
-- Mirrors lib/scouting-access.hasScoutingAccess: an active seattle_cup_scouting
-- entitlement for the user. SECURITY DEFINER so it can read feature_entitlements
-- rows for ANY user (the user's own SELECT policy only exposes their own rows).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.has_scouting_entitlement(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.feature_entitlements
    WHERE user_id = p_user_id
      AND feature_key = 'seattle_cup_scouting'
      AND status = 'active'
  );
$$;

GRANT EXECUTE ON FUNCTION public.has_scouting_entitlement(UUID) TO authenticated;

-- ---------------------------------------------------------------------------
-- activity_events: append-only activity feed. Author + meaningful action +
-- subject player (cross-database — the player lives in planit-ai, so no FK).
-- ---------------------------------------------------------------------------
CREATE TABLE public.activity_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- The PlanIt user who made the change. Denormalized display name so the inbox
  -- renders "Noah …" without a join; the authoritative actor identity is the
  -- user_id (FK to auth.users).
  actor_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  actor_display_name TEXT NOT NULL,
  feature TEXT NOT NULL,
  activity_type TEXT NOT NULL CHECK (
    activity_type IN ('note_added', 'candidate_state_changed', 'availability_changed')
  ),
  -- A planit-ai player id (stored as text — cross-database, no FK here). NULL
  -- only if a future activity type has no player subject; V1 always sets it.
  subject_player_id TEXT,
  subject_player_name TEXT,
  -- Structured, render-hinting metadata only. NOT authoritative domain state.
  -- candidate_state_changed: { from_state, to_state }
  -- availability_changed: { session_id, session_label, status, cleared }
  -- note_added:          { note_id, preview }
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX activity_events_feature_created_idx
  ON public.activity_events (feature, created_at DESC);

ALTER TABLE public.activity_events ENABLE ROW LEVEL SECURITY;

-- Only users with an ACTIVE seattle_cup_scouting entitlement may read scouting
-- activity. Supabase Realtime postgres_changes respects this SELECT policy, so
-- a non-entitled browser receives no events. All writes go through the
-- service-role client (server-side, in the planit.golf Server Actions), so there
-- are NO user INSERT / UPDATE / DELETE policies — RLS denies user writes by
-- default.
CREATE POLICY "Scouting captains read scouting activity"
  ON public.activity_events FOR SELECT
  USING (public.has_scouting_entitlement(auth.uid()));

-- ---------------------------------------------------------------------------
-- activity_read_state: per-user, per-feature "last seen activity" boundary.
-- Unread for a feature = activity_events.created_at > last_seen_at. No per-item
-- read receipts. The composite key supports multiple future features.
-- ---------------------------------------------------------------------------
CREATE TABLE public.activity_read_state (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  feature TEXT NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, feature)
);

ALTER TABLE public.activity_read_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own read-state"
  ON public.activity_read_state FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "Users insert own read-state"
  ON public.activity_read_state FOR INSERT
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users update own read-state"
  ON public.activity_read_state FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Realtime: publish activity_events changes to subscribed browsers. Only
-- INSERTs occur in V1 (append-only); the table has a PK so the default
-- REPLICA IDENTITY is sufficient for the INSERT events RLS-scoped clients
-- receive. Guarded so re-running the migration is a no-op.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'activity_events'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.activity_events;
  END IF;
END $$;


-- ============================================================
-- SOURCE: assistant_proposals (already-deployed production schema)
-- ============================================================
-- Folded from 026_assistant_proposals.sql (commit 0c94e4f, "assistant:
-- Phase A foundation") which lives on feature/assistant-phase-a and was
-- deployed to production. Verified byte-for-byte against the linked prod
-- schema on 2026-07-31: both tables, all columns/defaults/nullability,
-- PKs/FKs (3), CHECK constraints (7), the two non-PK indexes, RLS
-- enablement, all 5 policies match exactly. No publication membership,
-- no triggers, no functions. These are Planit-owned objects that already
-- exist in prod, so they belong in the canonical production baseline —
-- they are NOT forward schema from prod's perspective. The
-- feature-branch 026_assistant_proposals.sql is historical as far as the
-- baseline branch is concerned and must NOT be re-merged as an
-- executable migration (see docs/migration-baseline-verification.md).

-- ---------------------------------------------------------------------------
-- assistant_proposals: one draft per turn. Owned by its author (RLS).
-- ---------------------------------------------------------------------------
CREATE TABLE public.assistant_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  author_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Aggregate lifecycle. 'pending' = not yet fully applied; 'partially_applied'
  -- = some ops failed/stale or some remain undecided; 'applied' = all
  -- approved/edited ops applied cleanly; 'rejected' = all ops rejected;
  -- 'superseded' = replaced by a revision (Phase C revision flow).
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'partially_applied', 'applied', 'rejected', 'superseded')),
  turn_intent TEXT NOT NULL
    CHECK (turn_intent IN ('question', 'action', 'info_only', 'mixed', 'needs_clarification')),
  summary_text TEXT NOT NULL DEFAULT '',
  -- Editable natural-language directive that drives (and re-drives)
  -- interpretation in the Phase C revision flow. Kept now so the column exists.
  instructions_text TEXT NOT NULL DEFAULT '',
  source_kind TEXT NOT NULL DEFAULT 'canned'
    CHECK (source_kind IN ('nl', 'file', 'revision', 'canned')),
  -- Provenance: e.g. { filename, row } for a file source, or { text } for nl.
  source_ref JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- NULL in Phase A (no model). A model id once Phase B lands.
  model_id TEXT,
  -- Model interpretation snapshot (turn intent reasoning, resolved entities,
  -- uncertainty flags). Stored for audit; not authoritative scouting state.
  interpretation JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Self-reference for the Phase C revision chain (superseded_by points
  -- forward to the newer proposal that replaced this one).
  superseded_by UUID REFERENCES public.assistant_proposals(id) ON DELETE SET NULL
);

CREATE INDEX assistant_proposals_author_idx
  ON public.assistant_proposals (author_user_id, created_at DESC);

ALTER TABLE public.assistant_proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authors read own proposals"
  ON public.assistant_proposals FOR SELECT
  USING (author_user_id = auth.uid());

CREATE POLICY "Authors insert own proposals"
  ON public.assistant_proposals FOR INSERT
  WITH CHECK (author_user_id = auth.uid());

CREATE POLICY "Authors update own proposals"
  ON public.assistant_proposals FOR UPDATE
  USING (author_user_id = auth.uid())
  WITH CHECK (author_user_id = auth.uid());

CREATE POLICY "Authors delete own proposals"
  ON public.assistant_proposals FOR DELETE
  USING (author_user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- assistant_proposal_ops: the typed ops in a proposal, with per-op human
-- decision + apply result. Access is inherited through proposal ownership
-- (the policy checks the parent proposal's author). target_player_id is a
-- planit-ai player id stored as text (cross-database, no FK).
-- ---------------------------------------------------------------------------
CREATE TABLE public.assistant_proposal_ops (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id UUID NOT NULL REFERENCES public.assistant_proposals(id) ON DELETE CASCADE,
  seq INTEGER NOT NULL,
  op_type TEXT NOT NULL CHECK (
    op_type IN ('SET_CANDIDATE_STATE', 'SET_AVAILABILITY', 'CLEAR_AVAILABILITY', 'ADD_NOTE')
  ),
  target_player_id TEXT NOT NULL,
  target_player_display TEXT NOT NULL DEFAULT '',
  -- Discriminated by op_type (see lib/assistant/schema.ts). NOT authoritative;
  -- the applier re-validates on read.
  payload JSONB NOT NULL,
  expected_current_state JSONB NOT NULL DEFAULT '{}'::jsonb,
  rationale TEXT NOT NULL DEFAULT '',
  confidence TEXT CHECK (confidence IN ('high', 'medium', 'low')),
  human_decision TEXT NOT NULL DEFAULT 'pending'
    CHECK (human_decision IN ('pending', 'approved', 'edited', 'rejected')),
  -- Present only when human_decision = 'edited'. Authoritative over payload
  -- at apply time (manual edits win; no model is re-run).
  edited_payload JSONB,
  apply_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (apply_status IN ('pending', 'applied', 'failed', 'stale', 'skipped')),
  apply_error TEXT,
  applied_at TIMESTAMPTZ,
  UNIQUE (proposal_id, seq)
);

CREATE INDEX assistant_proposal_ops_proposal_idx
  ON public.assistant_proposal_ops (proposal_id, seq);

ALTER TABLE public.assistant_proposal_ops ENABLE ROW LEVEL SECURITY;

-- Ops inherit access through their parent proposal's ownership. A captain can
-- only see / edit ops of proposals they own. (This also makes a non-owner op
-- row invisible, so setOpDecision on another captain's op is a no-op, not a
-- cross-user mutation.)
CREATE POLICY "Owners manage own proposal ops"
  ON public.assistant_proposal_ops FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.assistant_proposals p
      WHERE p.id = proposal_id AND p.author_user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.assistant_proposals p
      WHERE p.id = proposal_id AND p.author_user_id = auth.uid()
    )
  );
